spring.application.name=backend
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db_phonexis?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driverClassName=${DB_DRIVER:com.mysql.cj.jdbc.Driver}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=${DB_DIALECT:org.hibernate.dialect.MySQLDialect}
server.error.include-message=always
